export const year = [
    2022,
    2021,
    2020,
    2019,
    2018,
    2017,
    2016,
    2015,
    2014,
    2013,
    2012,
    2011,
    2010,
    2009,
    2008
]


export const city = [
  { city: "Mumbai" },
  { city: "Delhi" },
  { city: "Bangalore" },
  { city: "Hyderabad" },
  { city: "Ahmedabad" },
  { city: "Chennai" },
  { city: "Kolkata" },
  { city: "Surat" },
  { city: "Pune" },
  { city: "Jaipur" },
  { city: "Lucknow" },
  { city: "Kanpur" },
  { city: "Nagpur" },
  { city: "Indore" },
  { city: "Thane" },
  { city: "Bhopal" },
  { city: "Visakhapatnam" },
  { city: "Pimpri-Chinchwad" },
  { city: "Patna" },
  { city: "Vadodara" },
  { city: "Ghaziabad" },
  { city: "Ludhiana" },
  { city: "Agra" },
  { city: "Coimbatore" },
  { city: "Nashik" },
  { city: "Ranchi" },
  { city: "Faridabad" },
  { city: "Meerut" },
  { city: "Rajkot" },
  { city: "Kalyan-Dombivli" },
  { city: "Vasai-Virar" },
  { city: "Varanasi" },
  { city: "Srinagar" },
  { city: "Aurangabad" },
  { city: "Dhanbad" },
  { city: "Gurgaon" },
  { city: "Amritsar" },
  { city: "Navi Mumbai" },
  { city: "Allahabad" },
  { city: "Howrah" },
  { city: "Gwalior" },
  { city: "Jabalpur" },
  { city: "Vijayawada" },
  { city: "Jodhpur" },
  { city: "Salem" },
  { city: "Madurai" },
  { city: "Raipur" },
  { city: "Kota" },
  { city: "Chandigarh" },
  { city: "Guwahati" },
  { city: "Solapur" },
  { city: "Hubli–Dharwad" },
  { city: "Mysore" },
  { city: "Tiruchirappalli" },
  { city: "Bareilly" },
  { city: "Aligarh" },
  { city: "Tiruppur" },
  { city: "Moradabad" },
  { city: "Jalandhar" },
  { city: "Bhubaneswar" },
  { city: "Warangal" },
  { city: "Mira-Bhayandar" },
  { city: "Jalgaon" },
  { city: "Guntur" },
  { city: "Thiruvananthapuram" },
  { city: "Bhiwandi" },
  { city: "Saharanpur" },
  { city: "Gorakhpur" },
  { city: "Bikaner" },
  { city: "Amravati" },
  { city: "Noida" },
  { city: "Jamshedpur" },
  { city: "Bhilai" },
  { city: "Cuttack" },
  { city: "Firozabad" },
  { city: "Kochi" },
  { city: "Nellore" },
  { city: "Bhavnagar" },
  { city: "Dehradun" },
  { city: "Durgapur" },
  { city: "Asansol" },
  { city: "Rourkela" },
  { city: "Nanded" },
  { city: "Kolhapur" },
  { city: "Ajmer" },
  { city: "Akola" },
  { city: "Gulbarga" },
  { city: "Jamnagar" },
  { city: "Ujjain" },
  { city: "Loni" },
  { city: "Siliguri" },
  { city: "Jhansi" },
  { city: "Ulhasnagar" },
  { city: "Jammu" },
  { city: "Sangli-Miraj & Kupwad" },
  { city: "Mangalore" },
  { city: "Erode" },
  { city: "Belgaum" },
  { city: "Kurnool" },
  { city: "Ambattur" },
  { city: "Rajahmundry" },
  { city: "Tirunelveli" },
  { city: "Malegaon" },
  { city: "Gaya" },
  { city: "Tirupati" },
  { city: "Udaipur" },
  { city: "Kakinada" },
  { city: "Davanagere" },
  { city: "Kozhikode" },
  { city: "Maheshtala" },
  { city: "Rajpur Sonarpur" },
  { city: "Bokaro" },
  { city: "South Dumdum" },
  { city: "Bellary" },
  { city: "Patiala" },
  { city: "Gopalpur" },
  { city: "Agartala" },
  { city: "Bhagalpur" },
  { city: "Muzaffarnagar" },
  { city: "Bhatpara" },
  { city: "Panihati" },
  { city: "Latur" },
  { city: "Dhule" },
  { city: "Rohtak" },
  { city: "Sagar" },
  { city: "Korba" },
  { city: "Bhilwara" },
  { city: "Berhampur" },
  { city: "Muzaffarpur" },
  { city: "Ahmednagar" },
  { city: "Mathura" },
  { city: "Kollam" },
  { city: "Avadi" },
  { city: "Kadapa" },
  { city: "Anantapuram" },
  { city: "Kamarhati" },
  { city: "Bilaspur" },
  { city: "Sambalpur" },
  { city: "Shahjahanpur" },
  { city: "Satara" },
  { city: "Bijapur" },
  { city: "Rampur" },
  { city: "Rajpura" },
  { city: "Shimoga" },
  { city: "Chandrapur" },
  { city: "Junagadh" },
  { city: "Thrissur" },
  { city: "Alwar" },
  { city: "Bardhaman" },
  { city: "Kulti" },
  { city: "Nizamabad" },
  { city: "Parbhani" },
  { city: "Tumkur" },
  { city: "Khammam" },
  { city: "Uzhavarkarai" },
  { city: "Bihar Sharif" },
  { city: "Panipat" },
  { city: "Darbhanga" },
  { city: "Bally" },
  { city: "Aizawl" },
  { city: "Dewas" },
  { city: "Ichalkaranji" },
  { city: "Karnal" },
  { city: "Bathinda" },
  { city: "Jalna" },
  { city: "Eluru[26]" },
  { city: "Barasat" },
  { city: "Kirari Suleman Nagar" },
  { city: "Purnia" },
  { city: "Satna" },
  { city: "Mau" },
  { city: "Sonipat" },
  { city: "Farrukhabad" },
  { city: "Durg" },
  { city: "Imphal" },
  { city: "Ratlam" },
  { city: "Hapur" },
  { city: "Arrah" },
  { city: "Anantapur" },
  { city: "Karimnagar" },
  { city: "Etawah" },
  { city: "Ambarnath" },
  { city: "North Dumdum" },
  { city: "Bharatpur" },
  { city: "Begusarai" },
  { city: "New Delhi" },
  { city: "Gandhidham" },
  { city: "Baranagar" },
  { city: "Tiruvottiyur" },
  { city: "Pondicherry" },
  { city: "Sikar" },
  { city: "Thoothukudi" },
  { city: "Rewa" },
  { city: "Mirzapur" },
  { city: "Raichur" },
  { city: "Pali" },
  { city: "Ramagundam[28]" },
  { city: "Silchar" },
  { city: "Haridwar" },
  { city: "Vijayanagaram" },
  { city: "Tenali" },
  { city: "Nagercoil" },
  { city: "Sri Ganganagar" },
  { city: "Karawal Nagar" },
  { city: "Mango" },
  { city: "Thanjavur" },
  { city: "Bulandshahr" },
  { city: "Uluberia" },
  { city: "Katni" },
  { city: "Sambhal" },
  { city: "Singrauli" },
  { city: "Nadiad" },
  { city: "Secunderabad" },
  { city: "Naihati" },
  { city: "Yamunanagar" },
  { city: "Bidhannagar" },
  { city: "Pallavaram" },
  { city: "Bidar" },
  { city: "Munger" },
  { city: "Panchkula" },
  { city: "Burhanpur" },
  { city: "Kharagpur" },
  { city: "Dindigul" },
  { city: "Gandhinagar" },
  { city: "Hospet" },
  { city: "Nangloi Jat" },
  { city: "Malda" },
  { city: "Ongole" },
  { city: "Deoghar" },
  { city: "Chapra" },
  { city: "Puri" },
  { city: "Haldia" },
  { city: "Khandwa" },
  { city: "Nandyal" },
  { city: "Morena" },
  { city: "Amroha" },
  { city: "Anand" },
  { city: "Bhind" },
  { city: "Bhalswa Jahangir Pur" },
  { city: "Madhyamgram" },
  { city: "Bhiwani" },
  { city: "Berhampore" },
  { city: "Ambala" },
  { city: "Morbi" },
  { city: "Fatehpur" },
  { city: "Raebareli" },
  { city: "Khora, Ghaziabad" },
  { city: "Chittoor" },
  { city: "Bhusawal" },
  { city: "Orai" },
  { city: "Bahraich" },
  { city: "Phusro" },
  { city: "Vellore" },
  { city: "Mehsana" },
  { city: "Raiganj" },
  { city: "Sirsa" },
  { city: "Danapur" },
  { city: "Serampore" },
  { city: "Sultan Pur Majra" },
  { city: "Guna" },
  { city: "Jaunpur" },
  { city: "Panvel" },
  { city: "Shivpuri" },
  { city: "Surendranagar Dudhrej" },
  { city: "Unnao" },
  { city: "Chinsurah" },
  { city: "Alappuzha" },
  { city: "Kottayam" },
  { city: "Machilipatnam" },
  { city: "Shimla" },
  { city: "Adoni" },
  { city: "Udupi" },
  { city: "Katihar" },
  { city: "Proddatur" },
  { city: "Mahbubnagar" },
  { city: "Saharsa[30]" },
  { city: "Dibrugarh" },
  { city: "Jorhat" },
  { city: "Hazaribagh" },
  { city: "Hindupur" },
  { city: "Nagaon" },
  { city: "Hajipur" },
  { city: "Sasaram" },
  { city: "Giridih" },
  { city: "Bhimavaram" },
  { city: "Port Blair" },
  { city: "Kumbakonam" },
  { city: "Bongaigaon" },
  { city: "Dehri" },
  { city: "Madanapalle" },
  { city: "Siwan" },
  { city: "Bettiah" },
  { city: "Ramgarh" },
  { city: "Tinsukia" },
  { city: "Guntakal" },
  { city: "Srikakulam" },
  { city: "Motihari" },
  { city: "Dharmavaram" },
  { city: "Medininagar" },
  { city: "Gudivada" },
  { city: "Phagwara" },
  { city: "Pudukkottai" },
  { city: "Hosur" },
  { city: "Narasaraopet" },
  { city: "Suryapet" },
  { city: "Miryalaguda" },
  { city: "Anantnag" },
  { city: "Tadipatri" },
  { city: "Karaikudi" },
  { city: "Kishanganj" },
  { city: "Jamalpur" },
  { city: "Ballia" },
  { city: "Kavali" },
  { city: "Tadepalligudem" },
  { city: "Amaravati" },
  { city: "Buxar" },
  { city: "Tezpur" },
  { city: "Jehanabad" },
  { city: "Aurangabad" },
  { city: "Gangtok" },
  { city: "Vasco Da Gama" },
];